# Generated by Django 5.2.5 on 2025-09-01 00:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, unique=True)),
                ('capacidad_total', models.IntegerField(help_text='Capacidad total en m²')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('medida', models.CharField(choices=[('L', 'Litros'), ('M', 'Metros'), ('G', 'Gramos'), ('U', 'Unidades')])),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso'), ('NEW', 'Creado')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.datetime(2025, 8, 31, 20, 26, 26, 588473))),
                ('modulo', models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('BARES_SNACKS', 'Bares Snacks'), ('MANTENIMIENTO', 'Mantenimiento'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('RECURSOS_HUMANOS', 'Recursos Humanos'), ('RESERVACIONES', 'Reservaciones')], max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='almacen.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Producto',
                'verbose_name_plural': 'Movimientos de Producto',
            },
        ),
        migrations.CreateModel(
            name='SeccionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('REFRIGERACION', 'Cámara de Refrigeración'), ('CONGELACION', 'Cámara de Congelación'), ('SECO', 'Almacén Seco'), ('ESTANTERIAS', 'Estanterías'), ('CUARTO_FRIO', 'Cuarto Frío'), ('SILOS', 'Silos'), ('TANQUES', 'Tanques')], max_length=20)),
                ('capacidad', models.IntegerField(help_text='Capacidad en m²')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura en °C (si aplica)', max_digits=5, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, help_text='Humedad relativa % (si aplica)', max_digits=5, null=True)),
                ('esta_activa', models.BooleanField()),
                ('almacen_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='almacen.almacen')),
            ],
            options={
                'verbose_name': 'Sección de Almacén',
                'verbose_name_plural': 'Secciones de Almacén',
                'unique_together': {('almacen_fk', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='seccion_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='almacen.seccionalmacen'),
        ),
    ]
