# Generated by Django 5.2.5 on 2025-09-03 01:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('procesada', 'Procesada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='registrada', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('unit_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('procesada', models.BooleanField(default=False)),
                ('barco_id', models.IntegerField(blank=True, help_text='ID del barco que realiza la solicitud', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_or_product', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('countries', models.ManyToManyField(to='compras.paises')),
            ],
        ),
        migrations.CreateModel(
            name='CompraPorProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad', models.CharField(choices=[('kg', 'Kg'), ('und', 'Unidad'), ('l', 'Litro')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores')),
            ],
            options={
                'unique_together': {('proveedor', 'material')},
            },
        ),
        migrations.AddField(
            model_name='proveedores',
            name='materiales',
            field=models.ManyToManyField(through='compras.ProveedorMaterial', to='compras.material'),
        ),
        migrations.CreateModel(
            name='SolicitudCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('medida', models.CharField(max_length=20)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.solicitudcompra')),
            ],
        ),
    ]
