# Generated by Django 5.2.5 on 2025-08-30 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('unit_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_or_product', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('countries', models.ManyToManyField(to='compras.paises')),
                ('materiales', models.ManyToManyField(to='compras.material')),
            ],
        ),
    ]
