# Generated by Django 5.2.5 on 2025-09-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compralote',
            name='estado',
            field=models.CharField(choices=[('registrada', 'Registrada'), ('espera_revision', 'En espera por revisión'), ('exitosa', 'Exitosa'), ('defectuosa', 'Defectuosa'), ('cancelada', 'Cancelada')], default='registrada', max_length=20),
        ),
    ]
