# Generated by Django 5.2.5 on 2025-09-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='fecha',
        ),
    ]
