# Generated by Django 5.2.5 on 2025-09-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compralote_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compralote',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='compras.solicitudsubtipo'),
        ),
        migrations.AlterField(
            model_name='compralote',
            name='presupuesto_lote',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
