# Generated by Django 5.2.5 on 2025-09-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_remove_solicitudcompra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='barco_id',
        ),
    ]
