# Generated by Django 5.2.5 on 2025-09-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_solicitudcompraitem_subtipo_solicitudcompraitem_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='materiales',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='subtipo',
            field=models.CharField(blank=True, choices=[('CADUCABLE', 'Caducable'), ('NO_CADUCABLE', 'No caducable'), ('REFRIGERADO', 'Refrigerado'), ('NO_REFRIGERADO', 'No refrigerado'), ('BEBIDA', 'Bebida'), ('LICOR', 'Licor'), ('REPUESTOS', 'Repuestos'), ('LIMPIEZA', 'Materiales de limpieza'), ('MEDICOS', 'Materiales médicos'), ('ACTIVOS', 'Bienes activos')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='tipo',
            field=models.CharField(choices=[('COMIDA', 'Comida'), ('BIENES', 'Bienes')], default='BIENES', max_length=20),
        ),
    ]
