# Generated by Django 5.2.5 on 2025-09-05 03:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_proveedores_materiales_proveedores_subtipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSubtipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('subtipo', models.CharField(max_length=50)),
                ('procesada', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudcompraitem',
            name='solicitud',
        ),
        migrations.CreateModel(
            name='SolicitudSubtipoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad_a_comprar', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('medida', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('subtipo', models.CharField(max_length=50)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.solicitudsubtipo')),
            ],
        ),
        migrations.DeleteModel(
            name='SolicitudCompra',
        ),
        migrations.DeleteModel(
            name='SolicitudCompraItem',
        ),
    ]
