# Generated by Django 5.2.4 on 2025-08-21 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crucero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo_crucero", models.CharField(max_length=50)),
                ("codigo_identificacion", models.CharField(max_length=50, unique=True)),
                ("fecha_botadura", models.DateField()),
                ("fecha_adquisicion", models.DateField()),
                ("capacidad_pasajeros", models.PositiveIntegerField()),
                ("capacidad_tripulacion", models.PositiveIntegerField()),
                ("tonelaje", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "puntal",
                    models.DecimalField(
                        decimal_places=2, help_text="Altura (m)", max_digits=7
                    ),
                ),
                (
                    "eslora",
                    models.DecimalField(
                        decimal_places=2, help_text="Longitud (m)", max_digits=7
                    ),
                ),
                (
                    "manga",
                    models.DecimalField(
                        decimal_places=2, help_text="Ancho (m)", max_digits=7
                    ),
                ),
                ("bandera", models.CharField(max_length=50)),
                ("puerto_base", models.CharField(max_length=100)),
                (
                    "estado_operativo",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("mantenimiento", "En mantenimiento"),
                            ("viaje", "En viaje"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("modelo_motor", models.CharField(max_length=100)),
                (
                    "velocidad_maxima",
                    models.DecimalField(
                        decimal_places=2, help_text="Nudos", max_digits=6
                    ),
                ),
                ("ultimo_mantenimiento", models.DateField()),
                ("proximo_mantenimiento", models.DateField()),
                ("tipo_combustible", models.CharField(max_length=50)),
                (
                    "consumo_promedio_combustible",
                    models.DecimalField(
                        decimal_places=2, help_text="Litros/hora", max_digits=8
                    ),
                ),
                ("seguro_vigente", models.BooleanField(default=True)),
                ("fecha_vencimiento_seguro", models.DateField()),
                (
                    "certificado_sanitario",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "foto_barco",
                    models.ImageField(blank=True, null=True, upload_to="fotos_barco/"),
                ),
                (
                    "plano_barco",
                    models.ImageField(blank=True, null=True, upload_to="planos_barco/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("capacidad", models.PositiveIntegerField()),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="tipos_habitacion/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instalacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("restaurante", "Restaurante"),
                            ("bar", "Bar"),
                            ("piscina", "Piscina"),
                            ("entretenimiento", "Zona de entretenimiento"),
                            ("gimnasio", "Gimnasio"),
                            ("enfermeria", "Enfermería"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("capacidad", models.PositiveIntegerField()),
                ("ubicacion", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "crucero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instalaciones",
                        to="myApp.crucero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cubierta", models.CharField(max_length=20)),
                ("numero", models.CharField(max_length=20)),
                ("ocupada", models.BooleanField(default=False)),
                (
                    "crucero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="myApp.crucero",
                    ),
                ),
                (
                    "tipo_habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="habitaciones",
                        to="myApp.tipohabitacion",
                    ),
                ),
            ],
        ),
    ]
