# Generated by Django 5.2.4 on 2025-08-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crucero",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Crucero",
                "verbose_name_plural": "Cruceros",
            },
        ),
        migrations.RemoveField(
            model_name="crucero",
            name="consumo_promedio_combustible",
        ),
        migrations.AddField(
            model_name="crucero",
            name="certificado_seguridad",
            field=models.FileField(
                blank=True,
                help_text="Certificado de seguridad del crucero",
                null=True,
                upload_to="certificados/seguridad/",
            ),
        ),
        migrations.AddField(
            model_name="crucero",
            name="consumo_combustible",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Consumo promedio en litros/hora",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="certificado_sanitario",
            field=models.FileField(
                blank=True,
                help_text="Certificado sanitario vigente",
                null=True,
                upload_to="certificados/",
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="descripcion",
            field=models.TextField(
                blank=True, default="", help_text="Descripción general del crucero"
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="eslora",
            field=models.DecimalField(
                decimal_places=2, help_text="Longitud total (m)", max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="fecha_vencimiento_seguro",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="foto_barco",
            field=models.ImageField(
                blank=True,
                help_text="Foto principal del crucero",
                null=True,
                upload_to="fotos_barco/",
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="manga",
            field=models.DecimalField(
                decimal_places=2, help_text="Ancho máximo (m)", max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="modelo_motor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="plano_barco",
            field=models.ImageField(
                blank=True,
                help_text="Plano de distribución del crucero",
                null=True,
                upload_to="planos_barco/",
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="proximo_mantenimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="puntal",
            field=models.DecimalField(
                decimal_places=2, help_text="Altura desde quilla (m)", max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="seguro_vigente",
            field=models.BooleanField(
                default=False, help_text="Indica si el seguro está vigente", null=True
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="tipo_combustible",
            field=models.CharField(
                choices=[
                    ("diesel", "Diésel"),
                    ("gasolina", "Gasolina"),
                    ("gnl", "Gas Natural Licuado"),
                    ("hibrido", "Híbrido"),
                ],
                default="diesel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="tipo_crucero",
            field=models.CharField(help_text="Tipo de crucero", max_length=50),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="tonelaje",
            field=models.DecimalField(
                decimal_places=2, help_text="Toneladas de peso muerto", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="ultimo_mantenimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crucero",
            name="velocidad_maxima",
            field=models.DecimalField(
                decimal_places=2, help_text="Velocidad máxima en nudos", max_digits=6
            ),
        ),
    ]
