# Generated by Django 5.2.4 on 2025-08-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_alter_crucero_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crucero",
            name="tipo_crucero",
            field=models.CharField(
                choices=[
                    ("convencional", "Barco Crucero Convencional"),
                    ("mega", "Mega Barco Crucero"),
                    ("oceanico", "Barco Crucero Oceanico"),
                    ("lujo", "Barco Crucero de Lujo"),
                    ("pequeno", "Barco Crucero de Pequeño Tamaño"),
                    ("aventura", "Barco Crucero de Aventura"),
                    ("expedicionario", "Barco Crucero Expedicionario"),
                    ("fluvial", "Barco Crucero Fluvial"),
                ],
                default="convencional",
                help_text="Tipo de crucero",
                max_length=30,
            ),
        ),
    ]
